sudo: required

matrix:
  include:
  - os : linux
    addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"


script:
  - cd folly
  - sudo apt-get install g++ automake autoconf autoconf-archive libtool libboost-all-dev libevent-dev libdouble-conversion-dev libgoogle-glog-dev libgflags-dev liblz4-dev liblzma-dev libsnappy-dev make zlib1g-dev binutils-dev libjemalloc-dev libssl-dev pkg-config
  - sudo apt-get install libiberty-dev
  - autoreconf -ivf
  - ./configure
  - make
  - make check
  

before_install:
    - eval "${MATRIX_EVAL}"



branches:
  except:
    - /^debian\/\d/
