sudo: required
language: generic

services:
  - docker

script:
  - cd folly
  - sudo apt-get install g++ automake autoconf autoconf-archive libtool libboost-all-dev libevent-dev libdouble-conversion-dev libgoogle-glog-dev libgflags-dev liblz4-dev liblzma-dev libsnappy-dev make zlib1g-dev binutils-dev libjemalloc-dev libssl-dev pkg-config
  - sudo apt-get install libiberty-dev
  - autoreconf -ivf
  - ./configure
  - make
  - make check
  


branches:
  except:
    - /^debian\/\d/
